[build]
  ignore = "node ./scripts/netlify-ignore-build.mjs meetings"
  command = "export DATABASE_URL=${NETLIFY_DATABASE_URL:-$DATABASE_URL} && pnpm install && NITRO_PRESET=netlify pnpm --filter meetings build"
  publish = "templates/meetings/dist"
  functions = "templates/meetings/.netlify/functions-internal"

[build.environment]
  NITRO_PRESET = "netlify"
  NPM_CONFIG_PRODUCTION = "false"
